# Generated by Django 5.1.7 on 2025-05-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='halltranslation',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('visitor', 'Visitor'), ('admin', 'Admin')], default='visitor', max_length=50),
        ),
    ]
