# Generated by Django 5.1.7 on 2025-05-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0002_chatlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='image_url',
        ),
        migrations.AddField(
            model_name='artifact',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artifacts/'),
        ),
    ]
