# Generated by Django 5.1.7 on 2025-05-14 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0003_remove_artifact_image_url_artifact_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='location',
        ),
        migrations.RemoveField(
            model_name='chatlog',
            name='user_id',
        ),
        migrations.AddField(
            model_name='artifact',
            name='material',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='register_number',
            field=models.CharField(default=123, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatlog',
            name='user',
            field=models.ForeignKey(default=321, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('event', 'Event'), ('workshop', 'Workshop')], default=12, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Artifact3DModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_file', models.FileField(upload_to='3d_models/')),
                ('description', models.TextField(blank=True, null=True)),
                ('artifact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='model3d', to='museum.artifact')),
            ],
        ),
        migrations.CreateModel(
            name='EventBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='museum.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='artifact',
            name='hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='museum.hall'),
        ),
        migrations.CreateModel(
            name='InteractiveMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coordinate', models.FloatField()),
                ('y_coordinate', models.FloatField()),
                ('hall', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='map', to='museum.hall')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museum.event')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('artifacts', models.ManyToManyField(to='museum.artifact')),
            ],
        ),
        migrations.DeleteModel(
            name='MapSection',
        ),
    ]
