# Generated by Django 5.1.7 on 2025-05-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0004_hall_remove_artifact_location_remove_chatlog_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='register_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hall',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
