# Generated by Django 5.1.7 on 2025-05-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0005_alter_artifact_register_number_alter_hall_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='register_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='hall',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
